# Generated by Django 3.0.7 on 2020-07-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.TextField(default=None),
        ),
    ]
