# Generated by Django 3.0.7 on 2020-07-20 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_album_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='images')),
                ('album_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Album')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
