# Generated by Django 3.0.7 on 2020-07-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200721_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='album_author',
            new_name='album_id',
        ),
    ]
