# Generated by Django 3.0.7 on 2020-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200721_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
